### ISSUE TITLE
EnumWindowsCallback Issue

### ISSUE THREAD

**Issue by Rencify** [guided-hacking/GH_D3D11_Hook#2]
Hello, so when I compiled the project I receive two errors: 
`declaration is incompatible with "BOOL EnumWindowsCallback(HWND hWnd, LPARAM lParam)" (declared at line 448) GH_D3D11_Hook`
and
`declaration is incompatible with "BOOL _stdcall EnumWindowsCallback(HWND hWnd, LPARAM lParam)" (declared at line 67) GH_D3D11_Hook`

Not quite too sure why this error is happening. I haven't messed around with the code, and I also have the latest Windows SDK.

Would be great if anyone could help, thanks! :)

EDIT: Seems like it's an issue when trying to compile the project as a 32-bit dll, the error goes away once compiling it as a 64 bit dll. Does anyone have any alternatives/solutions to make it work with 32-bit?

**Comment by GH-Rake** [comment]
change line 448 to:
BOOL CALLBACK EnumWindowsCallback( HWND hWnd, LPARAM lParam )

lemme know if it works

**Comment by Rencify** [comment]
Ah, that seemed to fix it. Thanks, Rake!
