### ISSUE TITLE
Game crash in bool HookD3D()

### ISSUE THREAD

**Issue by 860000023** [guided-hacking/GH_D3D11_Hook#3]
When the execution is complete return Hook(ogPresent, pTrampoline, PRESENT_STUB_SIZE);
The game crashed, what caused the problem? My system is win7. I run well on my friend's win7 and win10.
Hope to get your help

**Comment by GH-Rake** [comment]
You have a different version of D3D11.dll, you need to change stub size or fix relative address resolution

or you are using a overlay such as origin overlay, turn all overlays off, or follow the jump to hook the overlay.

**Comment by 860000023** [comment]
Thanks for your reply. I will try to find the reason

**Comment by 860000023** [comment]
I found the reason. It has nothing to do with your library. It is because I used pFW1Factory. Its FW1CreateFactory did not succeed. Do you have a better DrawText solution? By the way, when I use D3D11CreateDeviceAndSwapChain for D3D_DRIVER_TYPE_HARDWARE. Except for me None of the machines work. But I changed to D3D_DRIVER_TYPE_WARP and it worked well.

**Comment by GH-Rake** [comment]
I completely redid this project and fixed a bunch of stuff, it's posted here: https://guidedhacking.com/threads/directx11-how-to-hook-direct3d11-draw-template.15252/

I don't have text drawing tho.

**Comment by 860000023** [comment]
Thank you for sharing, it helped me a lot.
